# Generated by Django 3.1.4 on 2021-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210914_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='default.jpeg', upload_to='media/profile_images', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default_cover.jpeg', upload_to='media/blog_covers/%d.%m.%Y/', verbose_name='Обложка'),
        ),
    ]
