# Generated by Django 3.1.4 on 2021-09-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_tagbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagBase',
        ),
    ]
