# Generated by Django 3.1.4 on 2021-09-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_tagbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
