# Generated by Django 3.1.4 on 2021-09-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
