# Generated by Django 3.1.4 on 2024-08-26 12:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='None', max_length=250, verbose_name='Описание для продвижения'),
        ),
    ]
